version: '3'

services:
  cmake:
    container_name: cmake_container
    build:
      context: .
      dockerfile: Dockerfile
    
    tty: true
    command: /bin/bash

    volumes:
      - ./pydraco/testdata_files:/app/pydraco/testdata_files
      - ./plySampler:/app/plySampler
      - ./pydraco/src:/app/pydraco/src
