version: '3'

services:
  cmake:
    container_name: cmake_container
    build:
      context: .
      dockerfile: Dockerfile
    
    tty: true
    command: /bin/bash
    ports:
      - "12468:12468"
    volumes:
      - ./data:/app/data
      - ./plySampler:/app/plySampler
      - ./pydraco/src:/app/pydraco/src
    